name: TERRAFORM VCS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform-vcs:
    uses: hahomdal/gh-tf-wf-tests/.github/workflows/terraform-vcs.yml@v1
    with:
      tflint_repo: "terraform-linters/tflint-ruleset-google"
      tflint_repo_config_path: ""
    secrets:
      GHE_API_TOKEN: ${{ secrets.GHE_API_TOKEN }}
